# Generated by Django 5.1.3 on 2024-11-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_pet_adopted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('No Proespect Yet', 'No Prospect Yet')], default='Pending', max_length=25),
        ),
    ]
