# Generated by Django 5.1.3 on 2024-11-22 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_pet_adopted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='updated_at',
            new_name='approved_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='created_at',
            new_name='inquire_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='website.pet'),
        ),
    ]
