# Generated by Django 5.1.3 on 2024-11-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_updated_at_customer_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inquire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
