# Generated by Django 5.1.3 on 2024-11-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_customer_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('No Prospect Yet', 'No Prospect Yet')], default='Pending', max_length=25),
        ),
    ]
